lm_type: "Qwen/Qwen3-8B"
retrieval_type: "bm25"
test_dataset_name: "talkpl-ai/TalkPlayData-Challenge-Dataset"
item_db_name: "talkpl-ai/TalkPlayData-Challenge-Track-Metadata"
user_db_name: "talkpl-ai/TalkPlayData-Challenge-User-Metadata"
track_split_types:
  - "all_tracks"
user_split_types:
  - "all_users"
corpus_types:
  - "track_name"
  - "artist_name"
  - "album_name"
  - "release_date"
  - "tag_list"
cache_dir: "./cache"
device: "cuda"
attn_implementation: "flash_attention_2"
bm25_field_weights:
  track_name: 1
  artist_name: 1
  album_name: 1
  release_date: 1
  tag_list: 1
enable_query_rewrite: true
enable_specificity_routing: false
enable_user_to_item: false
